# Generated by Django 3.0.3 on 2020-02-17 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'refer_books',
            },
        ),
        migrations.CreateModel(
            name='ReferPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField()),
                ('content', models.FileField(upload_to='')),
                ('cover', models.FileField(upload_to='')),
                ('refer_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='refer_books', to='book.ReferBook')),
            ],
            options={
                'db_table': 'refer_pages',
            },
        ),
    ]
