# Generated by Django 3.0.3 on 2020-02-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200217_0626'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='referpages',
            table='refer_page',
        ),
    ]
