# Generated by Django 3.0.3 on 2020-02-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200217_0637'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='referpages',
            table='refer_pages',
        ),
    ]
